### ISSUE TITLE
[bug]: RPC password character error when upgrading from v25 to v26. LND cannot connect to it thereafter.

### ISSUE THREAD

**Issue by shojofigure** [Start9Labs/bitcoind-startos#134]
### Prerequisites

- [X] I have searched for existing issues that already report this problem.

### Device

Laptop/Desktop

### Device OS

Other

### Device OS Version

StartOS 0.3.5.1

### Browser

Chrome

### Browser Version

120

### Current Behavior

RPC password cannot use the exclamation mark "!" character anymore 

### Expected Behavior

RPC password cannot use the exclamation mark "!" character anymore 

### Steps to Reproduce

1. Install v25. Sync to 100% full node. Stop Bitcoin. Change RPC password with the "!" character in it. Start Bitcoin. Run LND (successful connection, all good).
2. Attempt to upgrade to v26
3. Error pop in Notifications; "Install of bitcoind@26.0.0 Failed: Config Generation Error: No Match: rpc.password: String "mypassword123!" Does Not Match Pattern ^[a-zA-Z0-9_]+$" (fyi the v26 is actually installed on startos)
5. Bitcoin v26 says "need config" to save a new password without "!" because it is not allowed. Save config with new password without "!" e.g. "mypassword123"
6. Run v26. LND now cannot connect to Bitcoin RPC. Bitcoin log says wrong password.
![startos-bitcoind](https://github.com/Start9Labs/bitcoind-startos/assets/134852413/90b19950-7600-4af6-a268-d24fbc7a2c26)

**Comment by k0gen** [comment]
@shojofigure 

We’ve identified an issue where changes to the bitcoind user or password can disrupt the operation of LND. This is due to the way LND reads RPC credentials and we are working on a fix for that.

However for now, there’s a simple solution to this:
1. Go to the LND service.
2. Click on `Config`.
3. Click `Save`.
4. Start the service.

By following these steps, your LND service should regenerate all credentials and continue to work as expected. We appreciate your understanding and patience as we work to improve our services.

**Comment by k0gen** [comment]
This issue is not related to Bitcoin but rather to the services that depend on it
- LND: [Issue #118](https://github.com/Start9Labs/lnd-startos/issues/118)
- CLN: [Issue #111](https://github.com/Start9Labs/cln-startos/issues/111)
