### ISSUE TITLE
[feat]: `mempoolfullrbf=1` by default

### ISSUE THREAD

**Issue by petertodd** [Start9Labs/bitcoind-startos#142]
### Prerequisites

- [X] I have searched for existing issues that already suggest this feature.

### Describe the Feature Request

Since about [90%+ of hashpower](https://github.com/bitcoin/bitcoin/pull/28132) is mining full-rbf, it makes sense to accept and relay those replacements.

### Describe the Use Case

Failing to accept and relay full-RBF replacements when almost all hash power accepts them decreases the accuracy of mempool fee estimation, and prevents users from learning about relevant transactions that are likely to get mined. This is particularly notable for users who are running block explorers on their Start 9 devices; why block explorer sites like https://mempool.space and https://blockstream.info have supported full-RBF for quite some time now.

### Describe Preferred Solution

Just set `mempoolfullrbf=1` by default; the configuration tool can continue to allow it to be disabled if desired. Bitcoin Core doesn't seem interested in doing this by default — likely politics around how controversial it has been. But there's no reason why we should not do the right thing for users.

**Comment by remcoros** [comment]
Contrary to my earlier statements (in another PR) about sticking with Core defaults. I think this one makes a lot of sense for (non-technical) users of 'full node providers' like StartOS and Umbrel.

Users of node distributions like this, do not normally follow the Bitcoin Core development, announcements and/or forums and completely rely on 'sane' defaults from these node providers.

Since it seems the network and users (not the core devs) have reached consensus about enabling mempoolfullrbf, and it improves end-user experience (fee estimation), this change makes sense to me.

Ack

**Comment by k0gen** [comment]
v26.1.0 will have `mempoolfullrbf=1` as default

**Comment by petertodd** [comment]
Thanks guys! Great to see full-rbf getting deployed more widely!
